(defconst my-svn-diff-buffer-name "*SVN Diff*")
(defconst my-svn-blame-buffer-name "*SVN Blame*")
(defconst svn-diff-command "svn 2>&1 diff -r")
(defconst svn-blame-command "svn blame")

(defun my-svn-blame ()
  (interactive)
  (view-buffer-other-window my-svn-blame-buffer-name)
  (other-window 1)
  (shell-command (concat svn-blame-command " " buffer-file-name) my-svn-blame-buffer-name)
  (other-window 1)
  (toggle-read-only))

(defun my-svn-diff (diff-option)
  (interactive)
  (view-buffer-other-window my-svn-diff-buffer-name)
  (diff-mode)
  (other-window 1)
  (shell-command (concat svn-diff-command diff-option " " buffer-file-name) my-svn-diff-buffer-name)
  (other-window 1)
  (toggle-read-only))

(defun my-svn-diff-prev ()
  (interactive)
  (my-svn-diff "PREV"))

(defun my-svn-diff-base ()
  (interactive)
  (my-svn-diff "BASE"))

(defun my-svn-diff-head ()
  (interactive)
  (my-svn-diff "HEAD"))
